[build-system]
requires = []
build-backend = "scikit_build_core.build"

[project]
name = "rcs_so101"
version = "0.5.2"
description="RCS SO101 module"
dependencies = [
    "rcs>=0.5.0",
    "lerobot==0.3.3",
]
readme = "README.md"
maintainers = [
  { name = "Tobias Jülg", email = "tobias.juelg@utn.de" },
]
authors = [
  { name = "Tobias Jülg", email = "tobias.juelg@utn.de" },
  { name = "Pierre Krack", email = "pierre.krack@utn.de" },
]
requires-python = ">=3.10"
license = "AGPL-3.0-or-later"

[tool.scikit-build]
build.verbose = true
build.targets = ["_core"]
logging.level = "INFO"
build-dir = "build"
wheel.packages = ["src/rcs_so101"]
install.components = ["python_package"]